version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./src:/go/src
    ports:
      - 5500:3000
    tty: true
  db:
    image: medico-lamp_mariadb55
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - "5306:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
volumes:
  data:
    external: true
    name: goforit
